services:
  guac-init:
    user: root 
    image: guacamole/guacamole:1.5.5
    # We'll share the same volume that MySQL will read from
    volumes:
      - guacamole-mysql-init:/init
    entrypoint: >
      /bin/sh -c "
      if [ ! -f /init/initdb.sql ]; then
        echo 'initdb.sql not found, generating...';
        /opt/guacamole/bin/initdb.sh --mysql > /init/initdb.sql;
        echo 'initdb.sql generated.';
      else
        echo 'initdb.sql already exists, skipping generation.';
      fi;
      echo 'Keeping the init container running...';
      while true; do sleep 60; done;
      "
    # Mark as healthy if initdb.sql exists
    healthcheck:
      test: ["CMD-SHELL", "[ -f /init/initdb.sql ] || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - guacamole-net

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-guac_db}
      MYSQL_USER: ${MYSQL_USER:-guac_dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - guacamole-mysql-data:/var/lib/mysql
      - guacamole-mysql-init:/docker-entrypoint-initdb.d
    networks:
      - guacamole-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  guacd:
    image: guacamole/guacd:1.5.5
    networks:
      - guacamole-net
    depends_on:
      - mysql

  guacamole:
    image: guacamole/guacamole:1.5.5
    depends_on:
      - guacd
      - mysql
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-guac_db}
      MYSQL_USER: ${MYSQL_USER:-guac_dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LDAP_HOSTNAME: ${LDAP_HOSTNAME}
      LDAP_PORT: 389
      LDAP_ENCRYPTION_METHOD: none
      LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      LDAP_SEARCH_BIND_DN: ${LDAP_SEARCH_BIND_DN}
      LDAP_SEARCH_BIND_PASSWORD: ${LDAP_SEARCH_BIND_PASSWORD}
      LDAP_USERNAME_ATTRIBUTE: ${LDAP_USERNAME_ATTRIBUTE:-sAMAccountName}
      MYSQL_AUTO_CREATE_ACCOUNTS: ${MYSQL_AUTO_CREATE_ACCOUNTS:-true}
      TOTP_ENABLED: ${TOTP_ENABLED:-true}
      TOTP_ISSUER: ${TOTP_ISSUER:-Apache Guacamole}
      TOTP_DIGITS: ${TOTP_DIGITS:-6}
      TOTP_PERIOD: ${TOTP_PERIOD:-30}
      TOTP_MODE: ${TOTP_MODE:-sha1}
    ports:
      - "3330:8080"
    volumes:
      - guacamole-config:/config
    networks:
      - guacamole-net

volumes:
  guacamole-mysql-data:
  guacamole-mysql-init:
  guacamole-config:

networks:
  guacamole-net:
